MTES-MCT/camino

- packages/ui/src/styles/buttons.css
- packages/ui/src/styles/system/typography.css
J'ai fais un tour rapide de l'application, j'ai pas vu d'autres régressions.
Après, je ne sais pas où se cachent tous les boutons.
Il faudrait continuer le mouvement d'enlever post-css sur les buttons parce qu'il y'a une confusion entre la classe .active et la pseudo-class :active dans le plugin. En gros, ça ne marche pas dans notre cas la pseudo-class :active et c'est pour ça qu'il y'avait tout ces "if" dans le code pour appliquer le style actif.
> fix(ui): les menus actifs sont à nouveau visibles

- Dockerfile.api
Je n'ai pas cherché pourquoi (surement un conflit de dependances), mais dateformat se retrouve dans node_modules de l'api, et non à la racine.
> fix(build): le docker de l'api fonctionne

- packages/api/src/tools/documents/files-index-build.ts
Le daily plante sauvagement avec 
```
2022-08-30 02:04:30 [error] Erreur durant le daily Error: Command failed: find ./packages/api/files | grep pdf
find: ./packages/api/files: No such file or directory
at checkExecSyncError (node:child_process:851:11)
at execSync (node:child_process:923:15)
at filesIndexBuild (/packages/api/dist/src/tools/documents/files-index-build.js:7:53)
at documentsCheck (/packages/api/dist/src/tools/documents/check.js:14:64)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async tasks (/packages/api/dist/src/daily_tasks.js:54:9) {
status: 1,
signal: null,
output: [
null,
<Buffer >,
<Buffer 66 69 6e 64 3a 20 2e 2f 70 61 63 6b 61 67 65 73 2f 61 70 69 2f 66 69 6c 65 73 3a 20 4e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 …
```
> fix(daily): récupère la liste des fichiers présents sur le disque

- infra/deploy.yml
- infra/roles/init/tasks/main.yml
On se retrouve avec des inconsistences entre les machines de dev, preprod et prod, où preprod et prod sont de très vieilles versions de docker
> chore(infra): Installe une version figée de docker sur les machines

- .github/workflows/api.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/common.yml
- .github/workflows/release-github.yml
- .github/workflows/ui.yml
- Makefile
Double objectif:
- simplifier le déploiement
- mieux découper la CI
Point bonus : On peut voir le job de déploiement directement dans le job de CI, ce n'est plus un "truc lancé en asynchrone à la fin de la CI"
> chore(infra): simplifie le déploiement automatique

- packages/api/src/business/rules-demarches/machine-helper.test.ts
En voulant analyser ce bug : https://mattermost.incubateur.net/camino/pl/76b4zrtzkjyo8dw6fg1z1wtjfr
J'ai vu qu'il manquait un test comme ça
> chore(test): ajoute un test sur le statut d'une démarche d'octroi d'ARM

- packages/common/src/static/titresTypesTypes_domaine_titresStatuts.test.ts
- packages/common/src/static/titresTypesTypes_domaine_titresStatuts.ts
- feat(titres): suppression de la table titresType--titreStatut
- feat(titres): affiche au publique les 'Permis Exclusifs de Carrière' dans le domaine des 'Carrières' lorsque le statut du titre est échu
> feat(titres): affiche au publique les 'Permis Exclusifs de Carrière' dans le domaine des 'Carrières' lorsque le statut du titre est échu

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/gitguardian.yml
- docs-sources/docs/04-deploiement/01-introduction.md
- package-lock.json
- package.json
L'idée est d'avoir deux branches : `preprod` et `prod` (à la place de `release-candidate`) pour déployer en preprod et en prod.
Ça sera, amha, plus simple de savoir quelle version est en preprod et en prod depuis notre repo github.
Point bonus, on a la notif sur notre channel quand la release est faite
fix #303
> infra(CI/CD): simplifie la livraison en preprod et prod

- .github/workflows/api.yml
- .github/workflows/common.yml
- .github/workflows/ui.yml
- Makefile
- packages/common/package.json
Problème : 
Chaque module a sa propre commande pour lancer le linteur.
Solution : 
On utilise la completion de Make pour faire `make lint/<tab><tab>` et voir sur quel module on lance le linteur
> chore(infra): déplace les linteurs dans le makefile

- packages/api/src/api/graphql/resolvers/metas.test.ts
- packages/api/src/api/graphql/resolvers/metas.ts
- packages/api/src/business/rules-demarches/machine-common.test.ts
- packages/api/src/business/rules-demarches/machine-common.ts
- packages/api/src/business/rules-demarches/machine-helper.ts
Dans le cas où il y'a une ARM mécanisée, on se retrouve à chercher les étapes possibles, et parmi elles il y'a la RDE.
la rde peut être avec mécanisation ou pas, avec franchissement ou pas (4 cas à tester), mais dans le cas où l'ARM est mécanisée, et qu'on teste si un rde non mécanisée est possible, on se retrouve dans un cas impossible pour lequel la machine throw une erreur.
Maintenant on catch cette erreur pour s'assurer qu'on ne fait que discarder cette étapetype/etapestatut
> fix(machines): les étapes possibles lors de l'ajout d'une étape ne plante en cas d'erreur de la machine

- packages/api/src/business/matrices.ts
> fix(matrices): le nom de la matrice 1402 fait apparaitre le nom de l'entreprise avant le slug

- packages/api/src/business/validations/titre-etape-updation-validate.ts
Bug découvert par Floriane, elle ne pouvait plus déclarer l'avis de la CARM
> fix(api): la creation d'une étape avec une durée héritée ignore la durée de l'étape

- packages/api/src/api/graphql/resolvers/titres.ts
- packages/api/src/api/graphql/schemas/index.graphql
- packages/api/src/api/rest/index.ts
- packages/api/src/database/queries/_titres-filters.ts
- packages/api/src/database/queries/titres.ts
- packages/common/src/static/facades.ts
- packages/common/src/static/pays.ts
- packages/ui/src/api/titres.js
- packages/ui/src/components/titres/filtres.js
- packages/ui/src/store/titres.js
Je ne suis pas sûr que le pays soit intéressant/pertinent car notre notion de pays est assez propre à Camino : 
```
BL: { id: 'BL', nom: "Collectivité d'outre-mer de Saint-Barthélemy" },
FR: { id: 'FR', nom: 'République Française' },
GF: { id: 'GF', nom: 'Département de la Guyane' },
GP: { id: 'GP', nom: 'Département de la Guadeloupe' },
MF: { id: 'MF', nom: "Collectivité d'outre-mer de Saint-Martin" },
MQ: { id: 'MQ', nom: 'Département de la Martinique' },
NC: { id: 'NC', nom: 'Nouvelle-Calédonie' },
PF: { id: 'PF', nom: 'Polynésie Française' },
PM: { id: 'PM', nom: 'Collectivité Territoriale de Saint-Pierre-et-Miquelon' },
RE: { id: 'RE', nom: 'Département de La Réunion' },
TF: { id: 'TF', nom: 'Terres Australes Françaises' },
WF: { id: 'WF', nom: 'Wallis-et-Futuna' },
XX: { id: 'XX', …
```
> feat(titre): filtre par communes, départements, régions, pays et façades maritimes

- packages/ui/src/components/_charts/chart-with-export.tsx
> fix(ui): le bouton de téléchargement de la donnée d'un graphe reste collé au graphe

- packages/ui/src/utils/documents.js
- packages/ui/src/utils/documents.test.js
> fix(document): ne peut pas supprimer un document lié à une étape

- packages/ui/src/components/etape/type-edit.tsx
On voit un warn lorsqu'on dev, mais en prod, ça bloque indéfiniment....
C'est dû au sort qui est "in place" et qui passe son temps à muter la props du composant typeahead, qui se re-render en boucle.
Très sympa de la part de vue de "juste" mettre un warn dans la console et de planter lamentablement en prod...
> fix(ui): ne bloque plus lors de la sélection des types d'étapes

- packages/api/src/server/rest.ts
> fix(api): les url de téléchargement des fichiers acceptent les routes commençant par '/' et '/download'

- packages/api/src/business/rules-demarches/definitions.ts
> fix(pex): les permis d'exploitations géothermie utilisent tous la machine, sauf 3 déjà présents et invalides

- infra/roles/devAndPreprod/templates/apply-prod
On a bien reçu le message, mais sans la date du snapshot, car on a oublié de sourcer les variables restic
> fix(infra): corrige la date du dernier snapshot appliqué sur l'environnement de dev

- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/documents.ts
Related to https://trello.com/c/zwMPsBwl/472-permettre-lajout-de-documents-sur-certaines-%C3%A9tapes
> feat(documents): ajoute le document 'avis' sur les étapes 'Avis du parc naturel marin' et Avis d'un président d'EPCI

- packages/ui/src/components/titre/header.tsx
> fix(ui): supprime le warning récurrent dans la console

- packages/api/src/index.ts
La DGEC nous a remonté le souci lors de la création de nouvelles démarches sur des titres avec des gros périmètres.
> fix(api): les utilisateurs peuvent envoyer des gros titres

- packages/ui/src/components/_common/perimetre.stories.tsx
- packages/ui/src/components/_common/perimetre.tsx
- packages/ui/src/components/_map/index.tsx
- packages/ui/src/components/_map/leaflet.ts
- packages/ui/src/components/_map/util.ts
- packages/ui/src/components/titres.tsx
- packages/ui/src/components/titres/mapUtil.ts
Avant : 
Après :
On passe d'un index.js à 1,587.35 kB vers 1,364.02 kB
Toute la partie leaflet se retrouve dans le fichier mapUtil-hash.js
> refactor(ui): les composants de carte sont chargés dynamiquement

- packages/ui/src/components/_common/perimetre.tsx
- packages/ui/src/components/_ui/dsfr-input-file.tsx
> fix(ui): améliore le glisser déposer et corrige la carte d’une étape

- infra/cd/Cargo.lock
- infra/cd/Cargo.toml
Related to:
* https://github.com/MTES-MCT/camino-issues-private/issues/5
> chore(cd): met à jour les dépendance de notre outil de CD

- packages/ui/src/components/titres/mapUtil.ts
> feat(carte): les marqueurs de carte solo s'affichent différemment

- packages/ui/src/router/index.ts
> fix(scroll): Scroll automatiquement en haut des pages suivantes et conserve le scroll lors des retours

- packages/api/package.json
- packages/ui/package.json
À voir pourquoi l'ui n'aime pas cette config
> chore(api): ajoute des warning quand on a pas des expressions booléenes strictes

- packages/ui/src/components/_ui/table-auto.tsx
- packages/ui/src/components/_ui/table.tsx
- packages/ui/src/components/activite.stories_snapshots_ACompleter.html
- packages/ui/src/components/activite.stories_snapshots_Deposable.html
- packages/ui/src/components/activite.stories_snapshots_Supprimable.html
- packages/ui/src/components/administration.stories_snapshots_Default.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_OkWithoutBlockedTitres.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithMultipleEntreprises.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithoutActivities.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithoutFiscalite.html
- packages/ui/src/components/dashboard/pure-onf-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-onf-dashboard.stories_snapshots_OkSansAttenteDeONF.html
- packages/ui/src/components/demarches/page.stories_snapshots_Demarches.html
- packages/ui/src/components/demarches/page.stories_snapshots_Loading.html
- packages/ui/src/components/demarches/page.stories_snapshots_Travaux.html
- packages/ui/src/components/demarches/page.stories_snapshots_WithError.html
- packages/ui/src/components/entreprise.stories_snapshots_Complet.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_AvecPagination.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Default.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Loading.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_WithError.html
- packages/ui/src/components/metas.stories_snapshots_Super.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Connected.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Loading.html
- packages/ui/src/components/utilisateurs.stories_snapshots_WithError.html
> fix(tableau): remplace le lien désactivé par un label dans l’entête des tableaux

- packages/ui/src/components/_common/perimetre.tsx
> fix(titre): corrige le téléchargement du périmètre après un changement de titre

- packages/api/package.json
- packages/api/src/api/rest/statistiques/dgtm.queries.ts
> fix(statistiques): les statistique de la DGTM n'utilisent plus les rapports en construction

- packages/api/src/business/rules/titre-phases-find.test.ts
- packages/api/src/business/rules/titre-phases-find.ts
> fix(phases): prend en compte les publications qui annulent une publication antérieure

- packages/api/src/api/rest/titres.queries.ts
- packages/api/src/business/processes/titres-activites-update.test.ts
- packages/api/src/business/processes/titres-activites-update.ts
- packages/common/src/permissions/titres.test.ts
- packages/common/src/permissions/titres.ts
- packages/common/src/static/facades.ts
- packages/common/src/territoires.test.ts
- packages/common/src/territoires.ts
- packages/ui/src/components/titre.tsx
On a rajouté les façades maritimes lors du calcul des pays rattachés au titre pour savoir si des activités sont attachées au titre ou non.
Aucun impact sur le daily
> chore(territoires): ajoute les façades maritimes au calcul des régions/pays pour savoir si il y'a des activités pour un titre

- infra/roles/camino/files/keycloak_theme/login/messages/messages_fr.properties
- infra/roles/camino/files/keycloak_theme/login/register.ftl
Pour Vincent --> On pourrait aller plus loin coté template et vérifier que l'erreur existe bien sur l'email et que c'est bien une erreur du type "email already exists", mais vu qu'on envoie les instructions par email, si la personne ne reçoit rien, elle reéssaiera je pense
> chore(keycloak): n'affiche plus le message indiquant qu'un utilisateur existe déjà

- infra/Makefile
- infra/cd/Cargo.lock
- infra/cd/Cargo.toml
Basé sur --> https://kobzol.github.io/rust/cargo/2024/01/23/making-rust-binaries-smaller-by-default.html
On est passé de 6Mo à un peu moins de 3Mo
> chore(cd): rend le livrable de CD plus petit

- packages/api/src/api/rest/__snapshots__/perimetre.test.integration.ts.snap
- packages/api/src/api/rest/perimetre.queries.ts
Apparemment c'est une des fonctions postGIS qu'on utilisait qui change l'ordre des points...
J'ai crée un gros périmètre pour tester les coordonnées, attention, il n'aime pas trop être importé dans camino, il y'a toutes les communes de l'héxagone haha)
[test_conversion.zip](https://github.com/MTES-MCT/camino/files/14196636/test_conversion.zip)
Liée à la :
* #755
> fix(perimetre): n'utilise plus ST_ReducePrecision qui, parfois, change les points de place

- packages/api/src/database/queries/_titres-filters.ts
- packages/api/src/database/queries/titres.ts
> chore(titres): optimise la requête qui calcule l’intersection

- packages/ui/src/components/statistiques/granulats-marins.stories_snapshots_Loading.html
- packages/ui/src/components/statistiques/granulats-marins.stories_snapshots_WithError.html
- packages/ui/src/components/statistiques/granulats-marins.tsx
> fix(statistiques): la page des granulats marins filtre correctement sur la page titres

- packages/ui/src/components/_map/leaflet.ts
- packages/ui/src/components/titres.tsx
- packages/ui/src/components/titres/map.tsx
- packages/ui/src/components/titres/mapUtil.ts
@pohayscamino Pour les préfectures, ça zoom sur la région et non sur le département.
Car c’est déjà assez « pénible » de récupérer les coordonnées de chaque région, alors pour les départements c’est encore pire.
> feat(carte): zoom automatique sur la carte pour les administrations

- packages/api/src/api/rest/titres.queries.ts
- packages/api/src/api/rest/titres.queries.types.ts
- packages/api/src/api/rest/titres.test.integration.ts
- packages/api/src/api/rest/titres.ts
- packages/api/src/business/utils/titre-slug-and-relations-update.ts
- packages/api/src/types.ts
> fix(titre): ne peut plus accéder au doublon après suppression

- packages/ui/src/components/_common/filtres.tsx
- packages/ui/src/components/_map/index.tsx
- packages/ui/src/router/index.tsx
Maintenant, on ne réinitialise plus la page quand on clique sur le lien d'une page sur laquelle on est.
Par exemple, sur la page "titres et autorisations", si on rajoute des filtres, puis qu'on clique sur le lien "titres et autorisations", ça réinitialisait tous les filtres, plus maintenant.
Corrige la:
* #1180
> fix(ui): le zoom automatique sur la région d'une administration est plus précis

- infra/roles/init/tasks/main.yml
En dev, preprod et prod, ça prend plus de 2G pour rien.
Pour vérifier que ça fonctionne bien, sur la machine, faire `sudo systemctl status systemd-journald` et on doit voir une ligne comme ça:
`System Journal (/var/log/journal/2ad851a335d342ae861ba1c6ca8c62fa) is 40.0M, max 1.0G, 983.9M free.`
> chore(infra): limite la taille du journal à 1G

- packages/api/src/api/rest/etapes.test.integration.ts
- packages/api/src/api/rest/etapes.ts
- packages/api/src/api/rest/logs.queries.ts
- packages/api/src/api/rest/logs.queries.types.ts
- packages/api/src/api/rest/titres.test.integration.ts
- packages/api/src/knex/migrations/20240530125050_add-logs.ts
- packages/api/src/server/rest.ts
Premier jet lié au plan de remédiation de la conformité au socle technique:
- #1152
Pour l'instant, pas d'IHM ni rien, juste une sauvegarde brut
En jouant un peu avec dans l'application, ça fonctionne bien, il n'y a pas de souci particulier.
Pour la route des documents par exemple, on ne sait pas quel est le PDF exact envoyé, mais on sait qui a fait quoi sur tel type de document, c'est largement suffisant.
Il nous faut migrer les requêtes graphql qui font des mutations (liste exhaustive):
- activite-deposer
- demarche-creer
- demarche-modifier
- demarche-supprimer
- titre-creer
- etape-creation
- etape-edition
> feat(api): enregistre les actions (mutations POST/PUT/DELETE) des utilisateurs

- infra/roles/prod/templates/backup
Ça ne sert plus à rien de sauvegarder les fichiers vu qu'il n'y a plus que tmp
> chore(infra): arrête la sauvegarde des fichiers temporaires

- packages/api/src/api/rest/__snapshots__/perimetre.test.integration.ts.snap
- packages/api/src/api/rest/perimetre.test.integration.ts
- packages/api/src/api/rest/perimetre.ts
- packages/common/src/perimetre.test.ts
- packages/common/src/perimetre.ts
On teste un decoding en UTF-8, s'il foire on teste un decoding en iso-8859-15.
> fix(perimetres): gérer l'iso-8859-15 des CSV

- packages/api/src/business/utils/titre-slug-and-relations-update.test.integration.ts
- packages/api/src/business/utils/titre-slug-and-relations-update.ts
> fix(titre): remet le bandeau des titres en doublon

- Dockerfile.api
> fix(infra): la nouvelle version de node/npm ne supporte pas les workspaces à la racine

- packages/api/src/api/rest/titres.ts
- packages/common/src/permissions/titres.test.ts
- packages/common/src/permissions/titres.ts
- packages/ui/src/components/titre.tsx
> fix(titres): permet administrations locales d'éditer un titre

- packages/api/src/api/_format/titres-etapes.ts
- packages/api/src/api/rest/etapes.ts
- packages/api/src/business/validations/utils/contenu-dates-check.test.ts
- packages/api/src/business/validations/utils/contenu-dates-check.ts
https://tchap.gouv.fr/#/room/!YAHYlwUZtOTEycSOFg:agent.dinum.tchap.gouv.fr/$9e5BQ9Tp_nOXVgDZGFDUuOJCyPVUAMFYCPHAZHhzXoc?via=agent.dev-durable.tchap.gouv.fr&via=agent.dinum.tchap.gouv.fr&via=agent.interieur.tchap.gouv.fr
> fix(etapes): corrige la validation des dates optionnelles de contenu

- packages/ui/src/components/_common/dsfr-perimetre.tsx
Les boutons de téléchargement sont alignés à droite.
Avant :
Après :
> fix(style): aligne correctement le bouton à droite

- packages/api/pgtyped-config.ci.json
- packages/api/pgtyped-config.json
- packages/api/src/@types/pg.types.ts
- packages/api/src/database/queries/communes.queries.types.ts
- packages/api/src/knex/migrations/20240730122244_ajouter-index-sur-geometry.ts
> feat(communes): ajout d'un index sur communes.geometry

- packages/api/src/business/utils/titre-etapes-sort.test.ts
- packages/api/src/business/utils/titre-etapes-sort.ts
Corrige le pb avec https://camino.beta.gouv.fr/titres/g-px-epinay-sous-senart-1996?demarcheSlug=g-px-epinay-sous-senart-1996-oct01
> fix(démarche): corrige le calcul d'ordre quand on a une demande en brouillon

- Makefile
- knip.ts
- packages/common/src/administrations.test.ts
- packages/common/src/static/departement.test.ts
- packages/common/src/static/phasesStatuts.test.ts
- packages/common/tsconfig.json
- packages/common/vitest.config.ts
Pour le passage à gitlab, on s'est dit qu'on allait se débarrasser de codecov, que personne ne regarde :)
On teste uniquement sur le common de ne pas faire baisser la couverture
> chore(common): force la couverture de code a toujours être égale ou supérieure à la précédente

- packages/api/src/api/rest/etapes.test.integration.ts
- packages/api/src/api/rest/etapes.ts
- packages/api/src/business/validations/titre-demarche-etat-validate.test.ts
- packages/api/src/business/validations/titre-demarche-etat-validate.ts
- packages/common/src/etape.ts
- packages/common/src/rest.ts
- packages/ui/src/components/etape-edition.stories.tsx
- packages/ui/src/components/etape/date-type-edit.stories.tsx
- packages/ui/src/components/etape/etape-api-client.ts
- packages/ui/src/components/etape/etape-edit-form.stories.tsx
- packages/ui/src/components/etape/type-edit.stories.tsx
- packages/ui/src/components/etape/type-edit.tsx
ça va nous simplifier le travail sur la PR de la procédure spécifique
> refactor(etapes): le format d'échange des étapes possibles à une date donnée est amélioré

- packages/api/src/api/rest/administrations.ts
- packages/api/src/api/rest/demarches.ts
- packages/api/src/api/rest/perimetre.ts
- packages/api/src/api/rest/titre-demande.ts
- packages/api/src/api/rest/utilisateurs.ts
- packages/api/src/server/rest.ts
- packages/ui/src/components/etape/type-edit.tsx
ils ont mis ça en place sur ma mission du vendredi, et je trouve ça plus lisible, et on peut ignorer les paramètres qu'on n'utilise pas
> refactor(api): on fait passer les paramètres dans un objet plutôt qu'à plat
