MTES-MCT/camino

- packages/ui/src/components/user/button.vue
> fix(ui): le bouton de l'utilisateur connecté ne lance plus d'avertissements dans la console

- packages/api/docs-sources/01-utilisation/04-flux.md
- packages/api/docs-sources/02-developpement/02-base-de-donnees.md
- packages/api/docs-sources/03-architecture/01-introduction.md
- packages/api/package.json
Fix https://trello.com/c/Vi5tOWwg/200-chore-faire-le-sch%C3%A9ma-darchitecture-pour-lhomologation
> fix(doc): les images locales sont embarquées dans la documentation

- packages/api/src/api/graphql/resolvers/_titre-etape.ts
Lié à la demande de Félix : https://docs.google.com/spreadsheets/d/13QWPT4-ixtyDRf53efA9RfxIEjhgozvw-4i6__bJteU/edit#gid=0
> feat(axm): rend la justification d'existence du gisement obligatoire en cas d'axm en zone 2 du SDOM

- packages/ui/src/utils/map-tiles.js
- fix(infra): la bonne configuration sentry est utilisée
- fix(ui): la carte du SDOM fonctionne à nouveua
> fix(ui): la carte du SDOM fonctionne à nouveau

- Dockerfile.api
- docker-compose.yml
- infra/deploy.yml
- infra/roles/user/tasks/main.yml
- packages/api/.gitignore
- packages/api/src/config/logger.ts
Pour Vincent du futur, je ne voulais pas là merger à la base, je voulais en discuter avant, mais pour la tester c'est beaucoup plus simple que je la merge.
On pourra la revert si ça ne te plait pas :)
> fix(infra): l'utilisateur git est utilisé dans l'image docker pour éviter les problèmes de droit

- packages/ui/src/components/titre/edit-popup.vue
Très agréable de se faire souiller par vue qui voit pas que les props obligatoires sont pas là et qui dit rien :'(
> fix(ui): corrige la popup d'édition de titre

- packages/ui/src/api/titre-demande.js
- packages/ui/src/components/titre-creation.vue
C'est dommage le diff n'est pas lisible avec la transformation en ts, mais au final il n'y a qu'un seul changement, dans la fonction save()
> fix(ui): peut créer un titre sans lier de titre

- packages/api/src/api/rest/entreprises.ts
- packages/api/src/knex/migrations-data/20220726122406_activites-fiscales-unites-fix.js
- packages/api/src/tools/api-openfisca/index.ts
- packages/common/src/static/substance.ts
- packages/common/src/static/unites.ts
- packages/ui/src/components/entreprise/__snapshots__/pure-entreprise-fiscalite.stories.storyshot
- packages/ui/src/components/entreprise/pure-entreprise-fiscalite.vue
- wip
- wip
- fix: fonctionne avec toutes les substances
> feat(fiscalite): ajoute les fiscalités autres que l'or guyanais

- packages/api/src/database/models/titres.ts
Encore des shenanigans avec Objection
> fix(api): la récupération des substances pour le téléchargement des CSV fonctionne

- packages/api/src/business/rules-demarches/machine-helper.ts
> fix(api): les étapes possibles d'un octroi fonctionne à nouveau

- Dockerfile.openfisca
- packages/api/src/api/rest/entreprises.test.integration.ts
- packages/api/src/api/rest/entreprises.ts
- packages/api/src/business/__snapshots__/matrices.test.ts.snap
- packages/api/src/business/matrices.ts
- packages/api/src/server/rest.ts
- packages/common/src/fiscalite.test.ts
- packages/common/src/fiscalite.ts
- packages/common/src/roles.ts
- packages/ui/src/components/entreprise.vue
- packages/ui/src/components/entreprise/__snapshots__/pure-entreprise-fiscalite.stories.storyshot
- packages/ui/src/components/entreprise/pure-entreprise-fiscalite.stories.ts
- packages/ui/src/components/entreprise/pure-entreprise-fiscalite.vue
Bloqué par https://github.com/openfisca/openfisca-france-fiscalite-miniere/pull/31
> fix(fiscalité): utilise openfisca avec les redevances 2022 à jour + corrige les matrices

- packages/api/src/api/graphql/resolvers/_titre-etape.ts
- packages/api/src/api/graphql/resolvers/points.ts
- packages/api/src/api/rest/statistiques.ts
- packages/api/src/business/processes/titres-etapes-areas-update.test.integration.ts
- packages/api/src/tools/geojson.ts
- packages/api/src/tools/territoires-update.ts
- packages/api/src/types.ts
- packages/common/src/date.test.ts
- packages/common/src/date.ts
- packages/common/src/static/sdom.ts
- packages/common/src/statistiques.ts
- packages/ui/src/api/client-rest.ts
- packages/ui/src/components/_charts/utils.ts
- packages/ui/src/components/dashboard.vue
- packages/ui/src/components/dashboard/__snapshots__/pure-dreal-dashboard.stories.storyshot
- packages/ui/src/components/dashboard/pure-dgtm-stats.vue
- packages/ui/src/components/dashboard/pure-dreal-dashboard.stories.ts
- packages/ui/src/components/dashboard/pure-dreal-dashboard.vue
- packages/ui/src/components/dashboard/testData.ts
- ajout des statistiques des titres déposés et octroyés en fonction de la zone du SDOM
- ajoute les statistiques des délais d'instruction
> feat(dashboard): ajoute des statistiques pour le dashboard de la DGTM

- infra/roles/user/tasks/devs.yml
- infra/roles/user/tasks/main.yml
- infra/roles/user/vars/main.yml
Désolé @vmaubert, tu vas avoir une demande de changement de mot de passe sur les machines :)
> feat(infra): les devs camino sont gérés via ansible

- packages/api/src/api/rest/statistiques.ts
- packages/ui/src/components/statistiques/pure-mineraux-metaux-metropole.vue
> feat(stats): ajoute l'unité sur le graphique du sel en métropole

- package-lock.json
- packages/ui/package.json
> chore(front): upgrade volar

- packages/api/src/database/queries/_titres-filters.ts
- fix(titres): peut chercher plusieurs substances
> fix(titres): peut chercher plusieurs substances

- .github/workflows/gitguardian.yml
- packages/api/src/api/rest/entreprises.ts
- packages/api/src/api/rest/statistiques.ts
- packages/common/src/date.test.ts
- packages/common/src/date.ts
- packages/common/src/statistiques.ts
- packages/ui/src/components/statistiques/pure-mineraux-metaux-metropole.NoStoryshots.stories.ts
- packages/ui/src/components/statistiques/pure-mineraux-metaux-metropole.vue
- feat(statistiques): ajout de la fiscalite
- add bauxite
- savepoint all substances
- ajoute fiscalité minière pour les substances fiscales sel
> feat(statistiques): ajoute la fiscalité minière à la bauxite et au sels

- packages/api/src/api/graphql/resolvers/statistiques-guyane.ts
- packages/api/src/api/graphql/schemas/statistiques.graphql
- packages/ui/src/api/statistiques.ts
- packages/ui/src/components/statistiques/guyane.vue
* suppression du bandeau "données en cours de collecte et consolidation" pour l'onglet 2021 ?
* suppression du graphe et indicateur 'Permis d'exploitation octroyés'
* modification des noms de section
> feat(statistiques): modifications sur l'onglet stat Guyane

- packages/api/src/api/rest/statistiques/dgtm.ts
- packages/api/src/api/rest/titres.ts
- packages/common/src/statistiques.ts
- packages/ui/src/components/dashboard/dgtm-stats.ts
- packages/ui/src/components/dashboard/pure-dgtm-stats-full.vue
- packages/ui/src/components/dashboard/pure-dgtm-stats.vue
- packages/ui/src/components/dashboard/testData.ts
- fix(dgtmDashboard): affiche les dernières étapes sur tous les titres et masque les prochaines étapes non importantes
- ajout sdom zone 3 pour stats
- mutualize delais instructions
- fix dgtm stats + beautiful graphs
- fix graph 3
- ajoute 4ème graphe
> feat(dgtmDashboard): corrige les différents graphes + rajoute des nouveaux

- packages/ui/src/components/_map/index.vue
- ui_nginx.conf
> feat(carte): ajoute la surcouche Limite de la redevance d’archéologie préventive à la carte

- packages/api/src/api/rest/utilisateurs.ts
> fix(utilisateurs): fix le téléchargement des utilisateurs si aucun filtre sur les rôles

- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/storybook.spec.ts
> fix(storybook): les tests attendent que les appels asynchrones soient effectués

- packages/api/src/tools/api-insee/fetch.test.ts
- packages/api/src/tools/api-insee/fetch.ts
- packages/api/src/tools/api-insee/index.ts
> fix(api): le token d'accès à l'insee n'est valide que 24 heures

- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/components/_ui/functional-loader.stories.tsx
- packages/ui/src/components/_ui/functional-loader.tsx
- packages/ui/src/components/dashboard/pure-dreal-dashboard.stories.tsx
- packages/ui/src/components/dashboard/pure-dreal-dashboard.tsx
> fix(dashboard): corrige le dashboard des DREAL

- infra/roles/user/vars/main.yml
> infra(utilisateur): supprime l'accès aux serveurs de bcousin

- packages/api/src/business/daily.ts
- packages/api/src/database/init.ts
- packages/api/src/knex/migrations-data/20230131155632_prm-sections-mod-engagement.ts
- packages/api/src/scripts/daily.ts
> fix(prm): ajoute l’engagement financier dans la modification de la demande

- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/__snapshots__/documents.test.ts.snap
- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/documents.ts
> feat(axm): la lettre de demande est obligatoire lors de l'étape 'demande' d'un 'octroi' d'AXM

- packages/api/src/api/graphql/resolvers.ts
- packages/api/src/api/graphql/resolvers/_titre-etape.ts
- packages/api/src/api/graphql/resolvers/metas-join.ts
- packages/api/src/api/graphql/resolvers/titres-etapes.ts
- packages/api/src/api/graphql/schemas/index.graphql
- packages/api/src/business/processes/titres-etapes-heritage-contenu-update.ts
- packages/api/src/business/processes/titres-etapes-ordre-update.ts
- packages/api/src/business/titre-etape-update.ts
- packages/api/src/business/utils/titre-etape-heritage-contenu-find.test.ts
- packages/api/src/business/utils/titre-etape-heritage-contenu-find.ts
- packages/common/src/static/facades.ts
- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/documents.ts
- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/index.ts
- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/sections.test.ts
- packages/common/src/static/titresTypes_demarchesTypes_etapesTypes/sections.ts
- packages/common/src/titres.ts
- packages/common/src/typescript-tools.ts
- packages/ui/src/api/metas.js
- packages/ui/src/components/_common/new-section-element.tsx
- packages/ui/src/store/metas-definitions.js
- refactor(tde): extrait les sections dans le common
- savepoint
- savepoint 2
- fix tests
- extract sections
> refactor(static): rend les sections statiques

- packages/common/src/titres.ts
> fix(titre): affiche correctement la devise de l’engagement financier

- packages/api/src/database/queries/permissions/documents.ts
- packages/ui/src/api/entreprises.js
- packages/ui/src/api/titres.js
- packages/ui/src/api/utilisateurs.js
- packages/ui/src/components/titre-creation.vue
- packages/ui/src/components/titres/filtres.js
- packages/ui/src/store/titres.js
- packages/ui/src/store/titres.test.js
- packages/ui/src/store/user.js
- packages/ui/src/store/user.test.js
> refactor(titre): simplifie la récupération des entreprises pouvant demander un titre

- packages/ui/src/components/demarches/filtres.js
> fix(démarches): corrige le fitrage sur les types et les statuts des titres

- packages/api/src/server/auth-basic.ts
> fix(qgis): les accès authentifiés à l'api pour QGis fonctionnent

- packages/ui/src/components/utilisateur.tsx
> fix(ui): un utilisateur peut être modifié par un super ou un admin

- packages/api/src/api/graphql/resolvers/utilisateurs.ts
- packages/api/src/api/graphql/utilisateurs.test.integration.ts
- packages/api/src/business/validations/utilisateur-updation-validate.test.ts
- packages/api/src/business/validations/utilisateur-updation-validate.ts
- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/components/utilisateur/edit-popup.tsx
> fix(utilisateur): un utilisateur ne peut pas modifier son rôle

- Makefile
- package-lock.json
- packages/ui/package.json
- packages/ui/src/components/journaux/differences.vue
- packages/ui/vite.config.js
> fix(journaux): utilise un fork de jsondiffpatch pour corriger le runtime

- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/components/_ui/card.tsx
- packages/ui/src/components/administration.tsx
- packages/ui/src/components/entreprise.tsx
- packages/ui/src/components/titre/administration.tsx
- packages/ui/src/components/utilisateur.tsx
> refactor(ui): transforme les accordéons statiques en 'card'

- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/components/_ui/alert.stories.tsx
- packages/ui/src/components/_ui/alert.tsx
- packages/ui/src/components/_ui/functional-popup.stories.tsx
- packages/ui/src/components/_ui/functional-popup.tsx
- packages/ui/src/components/titre.vue
- packages/ui/src/components/titre/demarche-edit-popup.tsx
- packages/ui/src/components/titre/demarche-remove-popup.tsx
- packages/ui/src/components/titre/edit-popup.tsx
- packages/ui/src/components/titre/header.tsx
- packages/ui/src/components/titre/remove-popup.tsx
- packages/ui/src/components/utilisateur/remove-popup.tsx
- packages/ui/src/dsfr.d.ts
- packages/ui/src/storybook.spec.ts
> feat(dsfr): migre certaine modale

- infra/roles/user/tasks/devs.yml
> fix(infra): changer les fichiers pour un utilisateur implique d'être sudoer

- packages/api/src/business/validations/titre-demarche-etat-validate.test.ts
- packages/api/src/business/validations/titre-demarche-etat-validate.ts
> fix(prm): on peut de nouveau déposer une demande

- packages/api/src/api/graphql/resolvers/metas.ts
- packages/api/src/api/rest/titres.ts
- packages/api/src/business/rules-demarches/arm/oct.machine.test.ts
- packages/api/src/business/rules-demarches/axm/oct.machine.test.ts
- packages/api/src/business/rules-demarches/axm/oct.machine.ts
- packages/api/src/business/rules-demarches/machine-helper.ts
- packages/api/src/business/rules-demarches/machine-test-helper.ts
- packages/api/src/business/rules-demarches/pxg/oct.machine.test.ts
> fix(axm): corrige l’ajout de l’avis de la DREAL

- package-lock.json
- packages/api/.prettierignore
- packages/api/config.json
- packages/api/package.json
- packages/api/src/api/rest/statistiques/dgtm.queries.ts
- packages/api/src/api/rest/statistiques/dgtm.queries.types.ts
- packages/api/src/api/rest/statistiques/dgtm.ts
- packages/api/src/business/processes/titres-etapes-areas-update.test.integration.ts
- packages/api/src/business/processes/titres-etapes-areas-update.ts
- packages/api/src/business/processes/titres-etapes-heritage-contenu-update.ts
- packages/api/src/knex/migrations-schema/20221021121056_delete-titres-administrations.ts
- packages/api/src/knex/migrations-schema/20221229082906_migre-sdomzones.ts
- packages/api/src/pg-database.ts
- packages/api/src/tools/geojson.ts
- packages/api/src/tools/territoires-update.ts
- packages/api/tests/db-manager.ts
- chore(api): utilise pg-typed
- fix deps
- refactor
> chore(api): utilise pg-typed pour remplacer knex et objection

- packages/api/src/business/validations/utilisateur-updation-validate.test.ts
- packages/common/src/permissions/__snapshots__/utilisateurs.test.ts.snap
- packages/common/src/permissions/utilisateurs.test.ts
- packages/common/src/permissions/utilisateurs.ts
> feat(utilisateur): un admin peut éditer les droits d’un admin

- Makefile
- packages/ui/src/components/titre/titres-link-form-api-client.ts
- packages/ui/src/components/titre/titres-link-form.stories.tsx
- packages/ui/src/components/titre/titres-link.stories.tsx
- packages/ui/src/components/titre/titres-link.tsx
- packages/ui/src/components/utilisateur/utilisateur-api-client.ts
> fix(titres): corrige la liaison de titres

- packages/api/src/business/daily.ts
- packages/api/src/business/titre-demarche-update.ts
- packages/api/src/business/titre-etape-update.ts
> fix(étape): met correctement à jour le statut d’un titre après l’ajout d’une étape

- package-lock.json
- packages/api/package.json
- packages/api/src/business/rules/titre-activites-build.ts
- packages/api/src/business/validations/utils/contenu-numbers-check.ts
- packages/common/package.json
- packages/common/src/static/activitesTypes.ts
- packages/ui/package.json
Since node 20.1 migration, we are impacted by this issue, it's quite painful https://github.com/npm/cli/issues/6399
> chore(build): met à jour typescript en version 5

- packages/ui/src/__snapshots__/storybook.spec.ts.snap
- packages/ui/src/components/page/header.tsx
> fix(menu): affiche l’onglet activités dans le menu pour les éditeurs

- Dockerfile.ui.storybook
- packages/ui/.storybook/preview.ts
- storybook_nginx.conf
> fix(storybook): les storybooks sont de nouveau accessibles

- packages/api/src/api/rest/statistiques/metaux-metropole.queries.ts
- packages/api/src/api/rest/statistiques/metaux-metropole.queries.types.ts
- packages/api/src/api/rest/statistiques/metaux-metropole.ts
- packages/common/src/static/departement.ts
- packages/common/src/static/substancesFiscales.ts
- packages/common/src/statistiques.ts
- packages/ui/src/components/statistiques/mineraux-metaux-metropole.stories_snapshots_Loading.html
- packages/ui/src/components/statistiques/mineraux-metaux-metropole.stories_snapshots_WithError.html
- packages/ui/src/components/statistiques/mineraux-metaux-metropole.tsx
Faut attendre de merger entreprise-get-rest et remettre celle là sur master
> fix(statistiques): les statistiques métaux métropole ne sont plus sensibles aux gros chiffres

- packages/ui/src/components/titre/header.tsx
> fix(ui): rafraichit la date de dernière modification au changement de titre

- .github/workflows/api.yml
- .github/workflows/common.yml
- .github/workflows/deploy.yml
- .github/workflows/graphql.yml
- .github/workflows/ui.yml
- Dockerfile.api
- Dockerfile.ui
- package.json
Plus besoin du fix npm pour que la CI remonte une erreur en cas de problème
> feat(node): met à jour node en 20.3

- packages/api/src/api/_format/etapes-types.ts
- packages/api/src/api/rest/etapes.ts
> fix(api): les étapes proposées quand on n'utilise pas de machine fonctionnent

- ui_nginx.conf
> fix(ui): ajoute tile.openstreetmap.org et tile.openstreetmap.fr aux CSP

- packages/ui/src/utils/titre-etape-heritage-build.js
Correctif du bug remonté par Jean-Raymond sur Terre H2
Je ne suis pas sûr que le bout de code serve encore (d'où le TODO) mais l'étape est passée 'as is' dans pleins de sous-composants qui sont sans typage, à réecrire en tsx avant d'y toucher peut être
> fix(ui): on peut déclarer une étape avec des justificatifs d'entreprise après une demande

- packages/ui/src/app.tsx
- packages/ui/src/components/page/header.stories.tsx
- packages/ui/src/components/page/header.stories_snapshots_Deconnecte.html
- packages/ui/src/components/page/header.tsx
> fix(ui): restaure correctement l’url après une authentification

- package-lock.json
- packages/ui/package.json
- packages/ui/src/storybook.spec.ts
Related to https://github.com/storybookjs/testing-vue3/pull/13
All our `*.ts` storybook files currently fail
> chore(ui): update @storybook/testing-vue3 to support storybook 7

- packages/ui/src/components/_ui/filters/filters-input.tsx
Related to:
- #617
Fixes https://github.com/MTES-MCT/camino/pull/617#issuecomment-1691596798
> fix(ui): les champs libres dans les filtres se mettent à jour à chaque caractère entré par l'utilisateur

- packages/ui/src/components/activite-edition.vue
> fix(activité): corrige le nom du type de document

- packages/api/src/api/graphql/administrations-permissions-demarches.test.integration.ts
- packages/api/src/api/graphql/administrations-permissions-titres.test.integration.ts
- packages/api/tests/_utils/administrations-permissions.ts
- packages/common/src/permissions/__snapshots__/titres.test.ts.snap
- packages/common/src/static/__snapshots__/administrationsTitresTypes.test.ts.snap
- packages/common/src/static/administrationsTitresTypes.ts
- packages/ui/src/components/statistiques/guyane.stories_snapshots_Loading.html
- packages/ui/src/components/statistiques/guyane.stories_snapshots_WithError.html
https://tchap.gouv.fr/#/room/!YAHYlwUZtOTEycSOFg:agent.dinum.tchap.gouv.fr/$v2QpkFitYME8o62LIUUO5Ci6LewLmJpcXy8aZn-69_s?via=agent.dinum.tchap.gouv.fr&via=agent.dev-durable.tchap.gouv.fr
> feat(droits): accorde la gestion des PER du domaine M à la DGEC

- packages/common/src/static/activitesTypesTitresTypes.test.ts
- packages/common/src/static/activitesTypesTitresTypes.ts
- packages/ui/src/components/titre.vue
> fix(ui): masque les activites pour un titre dont le type ne peut pas avoir d'activités

- packages/api/src/api/_format/titres.ts
- packages/api/src/api/graphql/schemas/titres.graphql
- packages/api/src/api/rest/index.ts
- packages/api/src/api/rest/statistiques/evolution-titres.queries.ts
- packages/api/src/database/models/_format/titre-insert.ts
- packages/api/src/database/queries/_titres-filters.ts
- packages/api/src/database/queries/graph/fields-format.ts
- packages/api/src/database/queries/permissions/titres-activites.ts
- packages/api/src/database/queries/permissions/titres.ts
- packages/api/src/database/queries/titres-demarches.ts
- packages/api/src/database/queries/titres.ts
- packages/api/src/knex/migrations/20230926083529_add-index-on-left-right.ts
- packages/api/src/types.ts
- packages/ui/src/api/fragments/titre.js
- packages/ui/src/components/dashboard/pure-dreal-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-dreal-dashboard.stories_snapshots_OkWithoutBlockedTitres.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithMultipleEntreprises.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithoutFiscalite.html
- packages/ui/src/components/entreprise.stories_snapshots_Complet.html
- packages/ui/src/components/titres.tsx
- packages/ui/src/components/titres/filtres.tsx
- packages/ui/src/components/titres/table-utils.ts
- fix(api): la requête sur les titres est plus rapide
- feat(carte): les administrations qui arrivent sur la carte ont des filtres prédéfinis
> feat(carte): les administrations qui arrivent sur la carte ont des filtres prédéfinis

- packages/ui/src/components/_common/page-header-content.tsx
- packages/ui/src/components/activites.stories_snapshots_Full.html
- packages/ui/src/components/activites.stories_snapshots_Loading.html
- packages/ui/src/components/administrations.stories_snapshots_Default.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_Loading.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_OkWithoutBlockedTitres.html
- packages/ui/src/components/dashboard/pure-administration-dashboard.stories_snapshots_WithError.html
- packages/ui/src/components/demarches/page.stories_snapshots_Demarches.html
- packages/ui/src/components/demarches/page.stories_snapshots_Loading.html
- packages/ui/src/components/demarches/page.stories_snapshots_Travaux.html
- packages/ui/src/components/demarches/page.stories_snapshots_WithError.html
- packages/ui/src/components/entreprises.stories_snapshots_Loading.html
- packages/ui/src/components/entreprises.stories_snapshots_NonConnecte.html
- packages/ui/src/components/entreprises.stories_snapshots_canCreateEntreprise.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_AvecPagination.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Default.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Loading.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_WithError.html
- packages/ui/src/components/metas.stories_snapshots_Super.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Connected.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Loading.html
- packages/ui/src/components/utilisateurs.stories_snapshots_WithError.html
-[ ] Vérifier que le bug dans la pièce jointe est corrigé
> fix(style): corrige l’alignement du bouton de création de demande

- packages/api/src/api/rest/index.ts
- packages/api/src/api/rest/utilisateurs.ts
- packages/common/src/filters.ts
- packages/common/src/rest.ts
- packages/ui/src/components/activites.stories_snapshots_Full.html
- packages/ui/src/components/activites.stories_snapshots_Loading.html
- packages/ui/src/components/demarches/page.stories_snapshots_Demarches.html
- packages/ui/src/components/demarches/page.stories_snapshots_Loading.html
- packages/ui/src/components/demarches/page.stories_snapshots_Travaux.html
- packages/ui/src/components/demarches/page.stories_snapshots_WithError.html
- packages/ui/src/components/entreprises.stories_snapshots_Loading.html
- packages/ui/src/components/entreprises.stories_snapshots_NonConnecte.html
- packages/ui/src/components/entreprises.stories_snapshots_canCreateEntreprise.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Connected.html
- packages/ui/src/components/utilisateurs.stories_snapshots_Loading.html
- packages/ui/src/components/utilisateurs.stories_snapshots_WithError.html
> refactor(téléchargement): supprime le format json

- packages/api/src/api/graphql/resolvers/titres-etapes.ts
> fix(api): les administrations locales qui ont le droit de créer des étapes, peuvent créer des étapes

- packages/ui/src/components/_ui/dsfr-input.tsx
- packages/ui/src/components/_ui/functional-popup.stories.tsx
- packages/ui/src/components/_ui/functional-popup.stories_snapshots_Main.html
- packages/ui/src/components/_ui/functional-popup.stories_snapshots_NotValid.html
- packages/ui/src/components/_ui/functional-popup.tsx
- packages/ui/src/components/activite/add-activite-document-popup.tsx
- packages/ui/src/components/activite/depose-popup.tsx
- packages/ui/src/components/activite/remove-popup.tsx
- packages/ui/src/components/entreprise/add-entreprise-document-popup.tsx
- packages/ui/src/components/entreprise/add-popup.tsx
- packages/ui/src/components/entreprise/edit-popup.tsx
- packages/ui/src/components/entreprise/remove-entreprise-document-popup.tsx
- packages/ui/src/components/titre/demarche-edit-popup.tsx
- packages/ui/src/components/titre/demarche-remove-popup.tsx
- packages/ui/src/components/titre/edit-popup.tsx
- packages/ui/src/components/titre/remove-popup.tsx
- packages/ui/src/components/utilisateur/remove-popup.tsx
> fix(entreprise): corrige la saisie de la description d’un document d’entreprise

- packages/common/src/static/couleurs.ts
- packages/ui/src/components/_common/filtres/types.stories_snapshots_AllTypes.html
- packages/ui/src/components/_common/perimetre.stories_snapshots_NoMap.html
- packages/ui/src/components/_common/titre-statut.stories_snapshots_All.html
- packages/ui/src/components/_common/titre-statut.tsx
- packages/ui/src/components/_ui/filters/filters-checkboxes.stories_snapshots_AllFilters.html
- packages/ui/src/components/_ui/filters/filters.stories_snapshots_AllFiltersClosedWithValues.html
- packages/ui/src/components/_ui/filters/filters.stories_snapshots_AllFiltersOpenedWithValues.html
- packages/ui/src/components/_ui/filters/filters.stories_snapshots_Opened.html
- packages/ui/src/components/activites.stories_snapshots_Full.html
- packages/ui/src/components/activites.stories_snapshots_Loading.html
- packages/ui/src/components/administration/permissions.stories_snapshots_Default.html
- packages/ui/src/components/demarches/page.stories_snapshots_Demarches.html
- packages/ui/src/components/demarches/page.stories_snapshots_Loading.html
- packages/ui/src/components/demarches/page.stories_snapshots_Travaux.html
- packages/ui/src/components/demarches/page.stories_snapshots_WithError.html
> fix(ui): utilise la même couleur pour les statuts des titres valides

- infra/roles/camino/templates/restore-last-backup
- infra/roles/prod/templates/backup
> fix(infra): les scripts shell s'arrêtent dès qu'une erreur est rencontrée

- packages/api/src/server/user-loader.ts
> fix(api): met à jour l'email si il a été changé depuis keycloak

- Dockerfile.api.docs
- Dockerfile.ui
- Dockerfile.ui.storybook
- packages/ui/src/components/_map/index.tsx
- ui_nginx.conf
> fix(cache): corrige les problèmes de cache

- packages/api/src/api/rest/format/titres-activites.ts
- packages/api/src/api/rest/index.ts
> feat(activités): ajoute une colonne qui contient le nom du titre dans l’export

- packages/api/src/api/graphql/schemas/index.graphql
- packages/api/src/database/queries/journaux.ts
- packages/common/src/journaux.ts
- packages/ui/src/components/journaux.tsx
- packages/ui/src/components/journaux/journaux-api-client.ts
- packages/ui/src/components/journaux/journaux.stories.tsx
- packages/ui/src/components/journaux/journaux.stories_snapshots_AvecPagination.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Default.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_Loading.html
- packages/ui/src/components/journaux/journaux.stories_snapshots_WithError.html
- packages/ui/src/components/journaux/journaux.tsx
Lié au redesign de la page 'Titre'
Related to #687
> feat(journaux): (super) Ajoute la possibilité de filtrer les journaux par titre

- packages/ui/src/components/_common/dsfr-perimetre.tsx
> fix(titre): corrige l’export du périmètre

- packages/ui/src/components/titre.tsx
> feat(ui): ajoute un message transient quand la suppression d'une étape ne fonctionne pas

- docker-compose.yml
- infra/roles/nginx/files/docker-compose.yml
- infra/roles/nginx/files/proxy.conf
- infra/roles/user/files/ssh_hardening.conf
- infra/roles/user/tasks/main.yml
Suite à l’audit de sécurité on a traité le points suivants : 
- Mise à jour de Nginx
- Suppression des suites de chiffrement faibles
- Correction de l’en-tête serveur
- Configuration de l’attribut de sécurité SameSite
- Durcissement de la politique de mot de passe
> feat(sécurité): améliore la sécurité de l’application

- package.json
- packages/api/src/api/graphql/administrations-permissions-demarches.test.integration.ts
- packages/api/src/api/graphql/administrations-permissions-titres.test.integration.ts
- packages/api/src/api/graphql/resolvers/titres-demarches.ts
- packages/api/src/api/graphql/schemas/titres-demarches.graphql
- packages/api/src/api/graphql/schemas/titres.graphql
- packages/api/src/api/rest/titres.ts
- packages/api/src/database/models/_format/titre-insert.ts
- packages/api/src/database/models/titres-demarches.ts
- packages/api/src/database/queries/permissions/administrations.ts
- packages/api/src/database/queries/permissions/titres-demarches.test.integration.ts
- packages/api/src/database/queries/permissions/titres-demarches.ts
- packages/api/src/database/queries/permissions/titres.test.integration.ts
- packages/api/src/database/queries/permissions/titres.ts
- packages/api/src/types.ts
- packages/api/tests/_utils/administrations-permissions.ts
- packages/api/tests/queries/titre.graphql
- packages/common/src/permissions/titres-demarches.ts
- packages/common/src/roles.ts
> refactor(titre): supprime les champs modification et suppression

- docs-sources/docs/01-utilisation/04-flux.md
- chore(keycloak): n'affiche plus le message indiquant qu'un utilisateur existe déjà (#922)
- doc(flux): mettre à jour la documentation sur les flux Camino
> 915 docflux mettre à jour la documentation sur les flux camino

- packages/common/src/static/forets.ts
Suite au monthly, on a 3 lignes d'erreur : 
> 2024-02-01 05:09:00 [error] une nouvelle forêt est apparue avec l'id 'FOS' et le nom 'Crique Fossée', il faut la rajouter dans le common
2024-02-01 05:09:01 [error] Le nom de la forêt STE a changé 'St Elie' --> Saint-Elie
2024-02-01 05:09:01 [error] les forêts ne sont pas à jour dans le common: 3PI,ZDUARBAL,ZDUARMAT,BSL,BSM,BEL,CHA,CORA,COUN,PTS,CKA,CPG,DBR,EGY,ZDUGABAL,ZDUGAKOU,GDS,KAW,LPS,LDD,MAL,MAN,MPA,PAR,MCA,MDF,MSO,MBV,NANC,ZDUPAFAV,ZDUPAMAC,PAP,PAUL,AMO,PTI,FRG,REG,RNNMAT,RNNNOU,RNNTRI,SAU,SGK,SLU,SPA,STE,STJ,SMA --> EGY,ZDUGAKOU,CKA,ZDUPAMAC,MBV,CHA,ZDUPAFAV,RNNMAT,COUN,RNNTRI,MAL,ZDUARMAT,BSL,RNNNOU,PAP,BSM,PTI,MAN,FRG,SGK,SPA,MPA,AMO,PAUL,MSO,DBR,STJ,SAU,LPS,REG,3PI,CORA,CPG,NANC,LDD,GDS,PAR,MCA,ZDUARBAL,BEL,SLU,MDF,ZDUGABAL,SMA,STE, …
> feat(forets): une nouvelle forêt (Crique Fossée) est apparue dans la cartographie de Guyane

- packages/api/src/api/rest/statistiques/metaux-metropole.queries.ts
> fix(stats): les statistiques de métropoles vont chercher les activités 'déposées' uniquement

- packages/api/src/api/rest/perimetre.ts
- packages/common/src/perimetre.ts
> fix(geojson): vérifie que la longitude et la latitude ont des valeurs cohérentes

- packages/ui/src/components/_common/dsfr-perimetre-table.tsx
- packages/ui/src/components/_common/geosysteme-typeahead.stories.tsx
- packages/ui/src/components/_common/geosysteme-typeahead.stories_snapshots_Default.html
- packages/ui/src/components/_common/geosysteme-typeahead.tsx
- packages/ui/src/components/etape/points-import-popup.stories_snapshots_Default.html
- packages/ui/src/components/etape/points-import-popup.tsx
> feat(geosysteme): uniformise la sélection du géosystème dans l'application

- packages/ui/src/components/_common/storybook.spec.ts
- packages/ui/src/components/_ui/storybook.spec.ts
À voir ce que ça donne sur la CI aussi
> chore(storyshots): divise les tests pour accélerer leur exécution

- packages/api/src/api/rest/titres.queries.ts
> fix(titre): affiche correctement le lien vers les activités sur la page d’un titre

- packages/ui/src/components/etape/perimetre-import-popup.stories_snapshots_Default.html
- packages/ui/src/components/etape/perimetre-import-popup.tsx
> fix(ui): typo

- packages/api/src/api/rest/perimetre.test.integration.ts
- packages/api/src/api/rest/perimetre.ts
- packages/ui/src/components/_common/dsfr-perimetre-table.tsx
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_CustomPoints.html
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_CustomPointsWithAnotherGeoSysteme.html
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_CustomPointsWithoutNameAndDesc.html
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_MultiplePolygonWithLacuneTableau.html
- packages/ui/src/components/_ui/dsfr-input-radio.stories.tsx
- packages/ui/src/components/_ui/dsfr-input-radio.stories_snapshots_Horizontal.html
- packages/ui/src/components/_ui/dsfr-input-radio.tsx
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmMecaniseDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmMecaniseNonDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmNonMecaniseDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeAvecGrosseNote.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeAvecSeulementPerimetre.html
- packages/ui/src/components/etape/perimetre-edit.stories_snapshots_FilledNoHeritage.html
- packages/ui/src/components/etape/perimetre-edit.stories_snapshots_Heritage.html
- packages/ui/src/components/etape/perimetre-import-popup.stories_snapshots_Default.html
- packages/ui/src/components/etape/perimetre-import-popup.tsx
- packages/ui/src/components/titre.stories_snapshots_AbattisKoticaOctroi.html
- packages/ui/src/components/titre.stories_snapshots_BasseManaMod.html
- packages/ui/src/components/titre.stories_snapshots_BonEspoirOctroi.html
- packages/ui/src/components/titre.stories_snapshots_BonEspoirProlongation2.html
- packages/ui/src/components/titre.stories_snapshots_ChantepieMutation.html
- packages/ui/src/components/titre.stories_snapshots_ChantepieOctroi.html
- packages/ui/src/components/titre.stories_snapshots_ChantepieOctroiAsEntreprise.html
- packages/ui/src/components/titre.stories_snapshots_CriqueAdolpheOctroi.html
- packages/ui/src/components/titre.stories_snapshots_Full.html
> chore(import): peut importer les csv que l'on génère

- packages/api/src/tools/territoires-update.ts
- packages/common/src/static/forets.ts
Meilleure visibilité du monthly
> fix(forets): suppression de crique fossé

- packages/api/src/scripts/generate-perimetres-origine.ts
- packages/common/src/static/geoSystemes.ts
- packages/ui/src/components/_common/dsfr-perimetre-table.tsx
- packages/ui/src/components/_common/dsfr-perimetre.stories.tsx
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_CustomPointsWithAnotherLegacyGeoSysteme.html
- packages/ui/src/components/etape/perimetre-edit.stories.tsx
- packages/ui/src/components/etape/perimetre-edit.stories_snapshots_LegacyGeoSysteme.html
- packages/ui/src/components/etape/perimetre-edit.tsx
Voici les périmètres qu’on a pas pu réinjecter pour diverses raisons, certains nécéssiteraient une correction manuelle : 
// un seul point opposable
'https://preprod.camino.beta.gouv.fr/etapes/ib3azhoNoXQHxd1Bnumak5ww',
// le contour commence à 2
'https://preprod.camino.beta.gouv.fr/etapes/FixGOMcVwkauQyH1byBKpglp',
// Devrait être plusieurs polygones
'https://preprod.camino.beta.gouv.fr/etapes/h4XRWr88Xa0YDMjPe3gVdhCd',
'https://preprod.camino.beta.gouv.fr/etapes/IXHTQEu5EX5QYqUzHV1tugjp',
'https://preprod.camino.beta.gouv.fr/etapes/mXvPgzER5mj3gLKnM0lLMs8R',
'https://preprod.camino.beta.gouv.fr/etapes/pTPoON8dWU4r4ylo8kerDNNe',
'https://preprod.camino.beta.gouv.fr/etapes/yBNXGAeopu8yFmM6LqbpnFtt',
// Les points sont surement pas le bon ordre …
> chore(périmètre): réinjecte les anciens périmètres

- packages/api/src/api/rest/__snapshots__/perimetre.test.integration.ts.snap
- packages/api/src/api/rest/demarches.queries.ts
- packages/api/src/api/rest/perimetre.queries.ts
- packages/api/src/api/rest/perimetre.test.integration.ts
- packages/api/src/api/rest/perimetre.ts
- packages/api/src/scripts/generate-perimetres-origine.ts
- packages/api/src/types.ts
- packages/common/src/demarche.ts
- packages/common/src/etape.ts
- packages/common/src/perimetre.ts
- packages/common/src/rest.ts
- packages/common/src/static/geoSystemes.ts
- packages/ui/src/components/_common/dsfr-perimetre-table.tsx
- packages/ui/src/components/_common/dsfr-perimetre.stories.tsx
- packages/ui/src/components/_common/dsfr-perimetre.stories_snapshots_CustomPointsWithAnotherLegacyGeoSysteme.html
- packages/ui/src/components/_common/dsfr-perimetre.tsx
- packages/ui/src/components/_common/geosysteme-typeahead.stories.tsx
- packages/ui/src/components/_common/geosysteme-typeahead.stories_snapshots_Default.html
- packages/ui/src/components/_common/geosysteme-typeahead.tsx
- packages/ui/src/components/etape/perimetre-edit.stories.tsx
- packages/ui/src/components/etape/perimetre-edit.stories_snapshots_LegacyGeoSysteme.html
- packages/ui/src/components/etape/perimetre-edit.tsx
- packages/ui/src/components/etape/perimetre-import-popup.tsx
- packages/ui/src/components/etape/points-import-popup.tsx
- packages/ui/src/components/titre/perimetre-api-client.ts
On a mis une jolie liste dans la pull request avec des périmètres complètement barrés :)
Si t'as envie de t'amuser à les corriger @pohayscamino :smile:
> chore(perimetre): génère plus de périmètres

- packages/common/src/perimetre.ts
- packages/ui/src/components/demarche/demarche-map.tsx
- packages/ui/src/components/etape/perimetre-edit.stories.tsx
- packages/ui/src/components/etape/perimetre-edit.stories_snapshots_WithForages.html
En attente de la validation du design par @pohayscamino 
Mais la review est possible
> feat(géothermie): améliore le design les forages

- packages/ui/src/components/demarche/demarche-map.tsx
- packages/ui/src/components/titres/mapUtil.ts
- feat(géothermie): améliore le design les forages (#1101)
- fix(cartes): corrige le calque des Titres Valides
> fix(cartes): corrige le calque des Titres Valides

- packages/ui/src/components/etape-edition.stories_snapshots_AffichageAide.html
- packages/ui/src/components/etape-edition.stories_snapshots_AxmEnZoneDuSdom.html
- packages/ui/src/components/etape-edition.stories_snapshots_Creation.html
- packages/ui/src/components/etape-edition.stories_snapshots_DemandeArmComplete.html
- packages/ui/src/components/etape-edition.stories_snapshots_Modification.html
- packages/ui/src/components/etape-edition.stories_snapshots_ModificationDemandeHeritee.html
- packages/ui/src/components/etape-edition.tsx
lié à https://github.com/MTES-MCT/camino/issues/1137#issuecomment-2110538142
> feat(ui): ajoute un lien vers la démarche lors de l'édition d'une étape

- packages/ui/src/styles/leaflet/overrides.css
> fix(carte): corrige le style des boutons sur la carte de la page d’accueil

- packages/api/src/api/rest/keycloak.ts
> fix(déconnexion): la déconnexion nous redirige vers la page d’accueil

- .gitignore
- knip.ts
- package.json
- packages/api/package.json
- packages/common/package.json
- packages/ui/package.json
- **chore(infra): accélère tsc avec la transpilation incrémentale**
- **better knip configuration**
- **really better knip configuration**
> chore(infra): accèlére la tsc en activant l'incremental build

- packages/common/src/static/forets.ts
Suite au monthly, on voit qu'il y'a 2 forêts qui ont disparu, et une qui vient d'apparaitre
> feat(forets): met à jour les forêts de Guyane

- packages/common/src/titres.test.ts
- packages/common/src/titres.ts
Lié au problème d'Émilien:
https://tchap.gouv.fr/#/room/!YAHYlwUZtOTEycSOFg:agent.dinum.tchap.gouv.fr/$5vRMiN4S2RvhcTx4dN1ypmSTBQOzEwTRWi4H7eQfUk8?via=agent.dev-durable.tchap.gouv.fr&via=agent.dinum.tchap.gouv.fr&via=agent.interieur.tchap.gouv.fr
> fix(common): on utilise la demande en brouillon pour déterminer les propriétés fondamentales si c'est la seule étape

- packages/ui/src/components/dashboard.tsx
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_Ok.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithMultipleEntreprises.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithoutActivities.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.stories_snapshots_OkWithoutFiscalite.html
- packages/ui/src/components/dashboard/pure-entreprise-dashboard.tsx
> feat(dashboard): ouvre le dashboard aux bureaux d'études

- packages/api/src/api/rest/etapes.test.integration.ts
- packages/api/src/api/rest/etapes.ts
- packages/api/src/database/models/entreprises.ts
- packages/common/src/permissions/titres-etapes.test.ts
- packages/common/src/permissions/titres-etapes.ts
- packages/ui/src/components/demarche/demarche-etape.stories.tsx
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_AxmDeposableAvecDaeEtAsl.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeNonSupprimable.html
- packages/ui/src/components/demarche/demarche-etape.tsx
> fix(etapes): les titulaires ne peuvent pas supprimer leur démarche

- package-lock.json
- packages/ui/package.json
La version 1.12.0 du DSFR fait régresser le fonctionnement de la tab "Annuaire". Retour à la dernière version fonctionnelle connue.
> fix(header): corrige l'ouverture de l'onglet 'Annuaire'

- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_AxmDeposableAvecDaeEtAsl.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmMecaniseDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmMecaniseNonDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeArmNonMecaniseDeposable.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeMultipleEntreprisesDocuments.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_DemandeNoMap.html
- packages/ui/src/components/demarche/demarche-etape.stories_snapshots_Depot.html
- packages/ui/src/components/etape-edition.stories_snapshots_AxmEnZoneDuSdom.html
- packages/ui/src/components/etape-edition.stories_snapshots_DemandeArmComplete.html
- packages/ui/src/components/etape/etape-documents-edit.stories_snapshots_Complet.html
- packages/ui/src/components/etape/etape-documents-edit.stories_snapshots_OctroiAxmUtilisateurEntreprise.html
- packages/ui/src/components/etape/etape-documents-edit.stories_snapshots_OctroiAxmUtilisateurEntrepriseComplet.html
- packages/ui/src/components/etape/etape-documents-edit.stories_snapshots_OctroiAxmUtilisateurSuper.html
- packages/ui/src/components/etape/etape-documents-edit.stories_snapshots_SdomZone.html
- packages/ui/src/components/etape/etape-documents-edit.tsx
- packages/ui/src/components/etape/etape-documents.stories_snapshots_NotConnected.html
- packages/ui/src/components/etape/etape-documents.stories_snapshots_UserAdministration.html
- packages/ui/src/components/etape/etape-documents.stories_snapshots_UserEntreprise.html
- packages/ui/src/components/etape/etape-documents.stories_snapshots_UserSuper.html
- packages/ui/src/components/etape/etape-documents.tsx
- packages/ui/src/components/etape/etape-edit-form.stories_snapshots_Default.html
Les documents pouvaient changer d'ordre suite à un update de l'étape.
Ils sont désormais triés par nom pour fixer l'ordre.
> feat(documents): trier les documents par nom/description

- package-lock.json
- packages/api/package.json
- packages/api/tsconfig.json
Sur ma machine, ça divise le temps par 2
> chore(api): accélère le redémarrage de l'api sur les postes de dév

- packages/api/src/api/rest/entreprises.queries.ts
- packages/api/src/api/rest/entreprises.queries.types.ts
- packages/api/src/business/processes/titres-activites-relance-send.test.ts
- packages/api/src/business/processes/titres-activites-relance-send.ts
- packages/api/src/business/processes/titres-activites-update.test.ts
- packages/api/src/business/processes/titres-activites-update.ts
- packages/common/src/roles.ts
Lors de la création de nouvelles activités, on ne notifie plus les bureaux d'études
> fix(emails): n'envoie plus les emails des activités aux bureau d'études

- packages/ui/src/components/_ui/tabs.stories.tsx
- packages/ui/src/components/_ui/tabs.stories_snapshots_WithoutIcon.html
- packages/ui/src/components/_ui/tabs.tsx
- packages/ui/src/components/entreprise.stories_snapshots_Complet.html
- packages/ui/src/components/entreprise.tsx
- packages/ui/src/components/entreprise/entreprise-fiscalite.stories_snapshots_Guyane.html
- packages/ui/src/components/entreprise/entreprise-fiscalite.stories_snapshots_GuyaneAnneePrecedente.html
- packages/ui/src/components/entreprise/entreprise-fiscalite.stories_snapshots_Loading.html
- packages/ui/src/components/entreprise/entreprise-fiscalite.stories_snapshots_Ok.html
- packages/ui/src/components/entreprise/entreprise-fiscalite.stories_snapshots_WithError.html
- packages/ui/src/components/entreprise/entreprise-fiscalite.tsx
- packages/ui/src/components/statistiques/guyane-activite.tsx
- packages/ui/src/components/statistiques/guyane.stories_snapshots_Loading.html
- packages/ui/src/components/statistiques/guyane.stories_snapshots_WithError.html
- packages/ui/src/components/statistiques/guyane.tsx
> refactor(tabs): utilise les tabs du DSFR

- docker-compose.yml
Toujours dû au problème de mise à jour de node
> fix(infra): corrige le docker-compose

- packages/api/src/api/rest/statistiques/guyane.ts
> fix(statistiques): corrige les stats de la Guyane

- packages/ui/src/components/etape/etape-edit-form.stories.tsx
- packages/ui/src/components/etape/etape-edit-form.stories_snapshots_EtapeDecisionAdministration.html
- packages/ui/src/components/etape/type-edit.tsx
> fix(étape): initialise correctement le statut lors de l'édition

- packages/ui/src/components/_ui/dsfr-input-checkboxes.tsx
Voir https://github.com/MTES-MCT/camino/pull/1385
> fix(activites): correction d'une boucle infinie

- packages/ui/src/components/statistiques/mineraux-metaux-metropole.tsx
> chore(ui): met à jour l'affichage de la fiscalité de bauxite et de sels

- docker-compose.local.yml
- docker-compose.yml
- infra/roles/nginx/files/docker-compose.yml
Il va falloir faire une manipulation manuelle sur les machines.
* En DEV/PREPROD: Restaurer les données depuis la prod
* En PROD:
- Arrêter l'api
- Faire une sauvegarde
- Mettre à jour l'infrastructure
- Appliquer la sauvegarde (ça va relancer l'API automatiquement)
> chore(infra): met à jour nginx-proxy, keycloak, oauth2, postgis

- package-lock.json
- packages/api/package.json
> chore(infra): met à jour sheetjs
